apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
spec:
  type: {{ .Values.hospitalApp.backend.service.type }}
  selector:
    app: hospital-app
    release: {{ .Release.Name }}
  ports:
    - port: {{ .Values.hospitalApp.backend.service.port }}
      targetPort: {{ .Values.hospitalApp.backend.service.port }}
