apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-hospital-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hospital-app
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: hospital-app
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Release.Name }}-sa
      containers:
      - name: frontend
        image: "{{ .Values.hospitalApp.frontend.image.repository }}:{{ .Values.hospitalApp.frontend.image.tag }}"
        ports:
        - containerPort: {{ .Values.hospitalApp.frontend.service.port }}
        command: ["npm", "run", "preview"]
        securityContext:
          runAsUser: 0
      - name: backend
        image: "{{ .Values.hospitalApp.backend.image.repository }}:{{ .Values.hospitalApp.backend.image.tag }}"
        ports:
        - containerPort: {{ .Values.hospitalApp.backend.service.port }}
        command: ["node", "server.js"]
        securityContext:
          runAsUser: 0
        env:
        - name: DB_URI
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-hospital-config
              key: DB_URI
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-hospital-secret
              key: JWT_SECRET
